#index:
#    path: /
#    controller: App\Controller\DefaultController::index

categorie:
  path: /home
  controller: App\Controller\QuizController::index
  
active:
  path: /active
  controller: App\Controller\SecurityController::active
  
