#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  path: /home
  controller: App\Controller\HomeController::index

categorie:
  path: /home/categorie
  controller: App\Controller\QuizController::index
  
