#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  path: /home
  controller: App\Controller\HomeController::index

categorie:
  path: /quiz/categorie
  controller: App\Controller\CategorieController::index
  
# show:
#   path: /home/show
#   controller: App\Controller\CategorieController::show